"""empty message

Revision ID: 0066a7e3eff2
Revises: 
Create Date: 2024-05-17 20:50:19.053770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0066a7e3eff2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaniya',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('baslama', sa.String(length=100), nullable=False),
    sa.Column('bitme', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cash', sa.Integer(), nullable=False),
    sa.Column('gracePeriod', sa.Integer(), nullable=False),
    sa.Column('CardMin', sa.Integer(), nullable=False),
    sa.Column('CardMax', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sorgu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Branch', sa.String(length=100), nullable=False),
    sa.Column('Service', sa.String(length=100), nullable=False),
    sa.Column('Date', sa.String(length=100), nullable=False),
    sa.Column('Time', sa.String(length=100), nullable=False),
    sa.Column('Phone', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sorgu')
    op.drop_table('scrool')
    op.drop_table('campaniya')
    # ### end Alembic commands ###
