"""empty message

Revision ID: fda798f01d58
Revises: 
Create Date: 2024-05-29 19:39:40.891159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda798f01d58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emanetler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('muddet', sa.Integer(), nullable=False),
    sa.Column('faiz', sa.Float(), nullable=False),
    sa.Column('valyuta', sa.String(length=100), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emanetler_sorgu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Radio', sa.String(length=100), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Sorname', sa.String(length=100), nullable=False),
    sa.Column('Phone', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xeberler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('data', sa.String(length=100), nullable=False),
    sa.Column('catecory', sa.String(length=100), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xeberler')
    op.drop_table('emanetler_sorgu')
    op.drop_table('emanetler')
    # ### end Alembic commands ###
